#!/data/data/com.termux/files/usr/bin/bash
if [ ! -f "/data/data/com.termux/files/usr/bin/arm" ]; then
	echo "  install necessary packages !"
	echo -e ""
#	pkg update -y && pkg install wget curl -y
if [ `uname -m`  == "aarch64" ]; then
		echo ""
		echo ""
		echo "  Architectural `uname -m`"
		echo "  Wait for Download arm-store `uname -m`"

		wget https://github.com/mr-73eeea/arm-store/blob/main/src/arm-aarch64.deb?raw=true -O /data/data/com.termux/files/usr/var/lib/arm-aarch64.deb > /dev/null 2>&1
		echo "  Wait for installing termux-root "
		dpkg -i /data/data/com.termux/files/usr/var/lib/arm-aarch64.deb > /dev/null 2>&1
		echo ""
		echo ""
elif [ `uname -m` == "armv8l" ]; then
		echo ""
		echo "  Architectural `uname -m`"
                echo "  Wait for Download arm-store `uname -m`"
		wget https://github.com/mr-73eeea/arm-store/blob/main/src/arm-armhf.deb?raw=true -O /data/data/com.termux/files/usr/var/lib/arm-armhf.deb > /dev/null 2>&1
		echo "  Wait for installing termux-root "
		dpkg -i /data/data/com.termux/files/usr/var/lib/arm/arm-armhf.deb > /dev/null 2>&1
		echo ""
		echo ""
fi
elif [ -f "/data/data/com.termux/files/usr/bin/arm" ]; then
echo ""
echo "updating termux-root"
echo ""

	if [ `uname -m`  == "aarch64" ]; then
		echo ""
		echo ""
		echo "  Architectural `uname -m`"
		echo "  Wait for Download arm-store `uname -m`"

		wget https://github.com/mr-73eeea/arm-store/blob/main/src/arm-aarch64.deb?raw=true -O /data/data/com.termux/files/usr/var/lib/arm-aarch64.deb > /dev/null 2>&1
		echo "  Wait for installing termux-root "
		dpkg -i /data/data/com.termux/files/usr/var/lib/arm-aarch64.deb > /dev/null 2>&1
		echo ""
		echo ""
	elif [ `uname -m` == "armv8l" ]; then
		echo ""
		echo "  Architectural `uname -m`"
                echo "  Wait for Download arm-store `uname -m`"
		wget https://github.com/mr-73eeea/arm-store/blob/main/src/arm-armhf.deb?raw=true -O /data/data/com.termux/files/usr/var/lib/arm-armhf.deb > /dev/null 2>&1
		echo "  Wait for installing termux-root "
		dpkg -i /data/data/com.termux/files/usr/var/lib/arm/arm-armhf.deb > /dev/null 2>&1
		echo ""
		echo ""
	fi


fi

